version: '2'
services:

# Our 1 of microservice
  fms:
    build: microservicepoc-fms
    ports:
    - "8081:8081"    
    links:
    - eureka

# Our 2nd microservice 
 assetcatalog:
    build: microservicepoc-assetcatalog
    ports:
    - "8072:8072"    
    links:
    - eureka
