version: '2'
services:

# Eureka server
  eureka:
    build: microservicepoc-eureka-server
    ports:
    - "8761:8761"
    
# Our 1 of microservice
  fms:
    build: microservicepoc-fms
    ports:
    - "8081:8081"    
    links:
    - eureka

# Our 2nd microservice 
 assetcatalog:
    build: microservicepoc-assetcatalog
    ports:
    - "8072:8072"    
    links:
    - eureka
