server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manish436/microserviceConfig